### ISSUE TITLE
Fail on a particular question

### ISSUE THREAD

**Issue by niallrobinson** [met-office-lab/weather-bot#55]
Is it going to be sunny this week?

Very good question Niall. Where though?

Exeter

Oops. Something went wrong and we need to start over.

**Comment by niallrobinson** [comment]
stack trace

```
.weather.variable - waterfall() step 11 of 12
.weather.variable - Session.beginDialog(weather.variable.sunny)
..weather.variable.sunny - waterfall() step 1 of 1
TypeError: Cannot read property 'emoji' of undefined
    at eval (eval at doT.template (/Users/niall/Projects/weather-bot/node_modules/dot/doT.js:133:11), <anonymous>:3:108)
    at applyModelToTemplate (/Users/niall/Projects/weather-bot/src/main/js/persona/index.js:22:20)
    at Object.getResponseForKeyWithScore [as getResponseForScore] (/Users/niall/Projects/weather-bot/src/main/js/persona/index.js:141:22)
    at Array.bot.dialog (/Users/niall/Projects/weather-bot/src/main/js/intents/weather/variableThresholdIntentBuilder.js:80:51)
    at /Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:67:39
    at next (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:92:21)
    at WaterfallDialog.beforeStep (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:99:9)
    at WaterfallDialog.doStep (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:61:14)
    at WaterfallDialog.begin (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:29:14)
    at Session.beginDialog (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/Session.js:254:16)
    at Array.bot.dialog (/Users/niall/Projects/weather-bot/src/main/js/intents/weather/variable.js:68:25)
    at /Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:67:39
    at next (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:92:21)
    at WaterfallDialog.beforeStep (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:99:9)
    at WaterfallDialog.doStep (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:61:14)
    at WaterfallDialog.dialogResumed (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:46:14)
    at skip (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:59:19)
    at Array.weather (/Users/niall/Projects/weather-bot/src/main/js/intents/utils/summarize.js:86:16)
    at /Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:67:39
    at next (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:92:21)
    at WaterfallDialog.beforeStep (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:99:9)
    at WaterfallDialog.doStep (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:61:14)
    at WaterfallDialog.dialogResumed (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:46:14)
    at skip (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:59:19)
    at Array.weather (/Users/niall/Projects/weather-bot/src/main/js/intents/utils/sanitze.js:203:16)
    at /Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:67:39
    at next (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:92:21)
    at WaterfallDialog.beforeStep (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:99:9)
    at WaterfallDialog.doStep (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:61:14)
    at WaterfallDialog.dialogResumed (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:46:14)
    at skip (/Users/niall/Projects/weather-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:59:19)
    at datapoint.getMethodForTargetTime.then (/Users/niall/Projects/weather-bot/src/main/js/intents/weather/variable.js:54:28)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
..weather.variable.sunny - ERROR: Cannot read property 'emoji' of undefined
..weather.variable.sunny - Session.endConversation()
Session.sendBatch() sending 2 message(s)
```

**Comment by tpowellmeto** [comment]
incorrect property indexing for emoji - now fixed
